#ifndef CONFIG_DSO_PLATTFORM 
#define  CONFIG_DSO_PLATTFORM 2022
#endif
#ifndef CONFIG_DSO_CHANNELS
#define  CONFIG_DSO_CHANNELS 2
#endif
#ifndef CONFIG_DSO_SAMPLING_FREQUENCY
#define  CONFIG_DSO_SAMPLING_FREQUENCY 1000000000
#endif
#ifndef CONFIG_DSO_INPUT_BIT_WIDTH
#define  CONFIG_DSO_INPUT_BIT_WIDTH 8
#ifndef CONFIG_DSO_TRIGGER_DATA_SIZE 
#define CONFIG_DSO_TRIGGER_DATA_SIZE 32
#endif

