##!/bin/bash
# Author: Alexander Lindert <alexander_lindert@gmx.at>
# Copyright 2010
# License GPLv2

echo -e "Open Source Digital Storage Oscilloscope configure script"
echo -e "Enter software the folder location if this file was moved to an external location!"
echo -e "     (eg. ../../../fpga/software)"
read DSOPATH
ls /dev/ttyS* /dev/ttyU*
echo -e "Enter your (serial) connection to programm the oscilloscope"
read UART

echo -e "Is this your simulation compilation folder (Y/N) (default: N)"
read SIM
if [-z $SIM ]; then
	SIM=Y
fi
case $SIM in
	Y)
	DSO_BOARD=SIM_COMPILATION
	;;
	*)
	DSO_BOARD=BOARD_COMPILATION
	;;
esac

echo -e "Enter your Target: (default: 1)"
echo -e "(1) Welec W2022A"
echo -e "(2) Welec W2024A (not supported at the moment)"
echo -e "(3) SandboxX (out of date)"
read TX
case $TX in
	3)
	TARGET=SBXX
	;;
	*)
	TARGET=W2000A
	;;
esac

echo -e "Makefile generation launched." 

echo -e "#Open Source Digital Storage Oocilloscope user compile configurations generated by configure.sh" > Makefile
echo -e "DSOPATH=$DSOPATH" >> Makefile
echo -e "UART=$UART" >> Makefile
echo -e "DSO_BOARD=$DSO_BOARD" >> Makefile
echo -e "TARGET=$TARGET" >> Makefile
echo -e "include ${DSOPATH}/Makefile.firmware" >> Makefile

echo -e "Makefile generation is done." 

# if you cannot execute this file you can generate your Makefile also manually with at 
# minimum these following lines (without the #):

#DSOPATH=.
#UART=COM3
#DSO_BOARD=BOARD_COMPILATION
#TARGET=W2000A
#include ./Makefile.firmware
