vcom {../../Scope/src/Global-p.vhd}
vcom {../../DownSampler/Octave/FastFirCoeff-p.vhd}
vcom {../../DownSampler/src/PolyphaseDecimator-p.vhd}
vcom {../../DownSampler/src/FastAverage-ea.vhd}
vcom {../../DownSampler/src/FastPolyPhaseDecimator-ea.vhd}
vcom {../../DownSampler/src/DownSampler-ea.vhd}
vcom {../../DownSampler/src/TopFastPolyPhaseDecimator-ea.vhd}
vcom {../../DownSampler/src/TopDownSampler-ea.vhd}
vcom {../../Trigger/src/Trigger-p.vhd}
vcom {../../Trigger/src/TriggerMemory-ea.vhd}
vcom {../../Trigger/src/NormalTrigger-ea.vhd}
vcom {../../Trigger/src/ExternalTrigger-ea.vhd}
vcom {../../Trigger/src/TopTrigger-ea.vhd}
vcom {../../TestFiles/src/Wavefiles-p.vhd}
vcom {../../Trigger/src/TestbenchTopTrigger-ea.vhd}
vsim Testbench
do wave.do
run -all
