#ifndef FONT_ARIAL_H
#define FONT_ARIAL_H

/*****************************************************************************
 * File: font_Arial_18.h generated by FontGen 1.0
 * Author:  Robert Schilling <robert.schilling at gmx.at>
 * Date: 12.02.2010, 09:38
******************************************************************************

*  Copyright (c) 2010, Robert Schilling

*  This program is free software; you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 2 of the License, or
*  (at your option) any later version.

*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.

*  You should have received a copy of the GNU General Public License
*  along with this program; if not, write to the Free Software
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA */

#include "DSO_Font.h"

extern sFont font_arial_18;


#endif
