	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/stdlib/version.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/stdlib/stdlib.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/stdlib/stdio.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/stdlib/testlib.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/util/util.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/sparc/sparc.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/sparc/sparc_disas.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/sparc/cpu_disas.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/modgen/multlib.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/modgen/leaves.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/amba.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/devices.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/defmst.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/apbctrl.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/ahbctrl.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/dma2ahb_pkg.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/dma2ahb.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/dma2ahb_tp.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/amba_tp.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/at/at_pkg.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/at/at_ahb_mst_pkg.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/at/at_ahb_slv_pkg.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/at/at_util.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/at/at_ahb_mst.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/at/at_ahb_slv.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/at/at_ahbs.vhd
	vcom -quiet  -93  -work grlib ../../grlib-W2000A/lib/grlib/amba/at/at_ahb_ctrl.vhd
	vcom -quiet  -93  -work altera ../../grlib-W2000A/lib/tech/altera/simprims/altera_primitives_components.vhd
	vcom -quiet  -93  -work altera ../../grlib-W2000A/lib/tech/altera/simprims/altera_primitives.vhd
	vcom -quiet  -93  -work altera_mf ../../grlib-W2000A/lib/tech/altera_mf/simprims/altera_mf_components.vhd
	vcom -quiet  -93  -work altera_mf ../../grlib-W2000A/lib/tech/altera_mf/simprims/altera_mf.vhd
	vcom -quiet  -93  -work dw02 ../../grlib-W2000A/lib/tech/dw02/comp/DW02_components.vhd
	vcom -quiet  -93  -work synplify ../../grlib-W2000A/lib/synplify/sim/synplify.vhd
	vcom -quiet  -93  -work synplify ../../grlib-W2000A/lib/synplify/sim/synattr.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/gencomp/gencomp.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/gencomp/netcomp.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/inferred/memory_inferred.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/inferred/ddr_inferred.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/inferred/mul_inferred.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/inferred/ddr_phy_inferred.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/dw02/mul_dw_gen.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/altera_mf/memory_altera_mf.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/altera_mf/clkgen_altera_mf.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/altera_mf/tap_altera_mf.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/allclkgen.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/allddr.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/allmem.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/allpads.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/alltap.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/clkgen.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/clkmux.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/clkand.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/ddr_ireg.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/ddr_oreg.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/ddrphy.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/syncram.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/syncram64.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/syncram_2p.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/syncram_dp.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/syncfifo.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/regfile_3p.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/tap.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/techbuf.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/nandtree.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/clkpad.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/clkpad_ds.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/inpad.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/inpad_ds.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/iodpad.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/iopad.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/iopad_ds.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/lvds_combo.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/odpad.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/outpad.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/outpad_ds.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/toutpad.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/skew_outpad.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/grspwc_net.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/grspwc2_net.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/grlfpw_net.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/grfpw_net.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/mul_61x61.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/cpu_disas_net.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/grusbhc_net.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/ringosc.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/ssrctrl_net.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/system_monitor.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/grgates.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/inpad_ddr.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/outpad_ddr.vhd
	vcom -quiet  -93  -work techmap ../../grlib-W2000A/lib/techmap/maps/iopad_ddr.vhd
	vcom -quiet  -93  -work eth ../../grlib-W2000A/lib/eth/comp/ethcomp.vhd
	vcom -quiet  -93  -work eth ../../grlib-W2000A/lib/eth/core/greth_pkg.vhd
	vcom -quiet  -93  -work eth ../../grlib-W2000A/lib/eth/core/eth_rstgen.vhd
	vcom -quiet  -93  -work eth ../../grlib-W2000A/lib/eth/core/eth_ahb_mst.vhd
	vcom -quiet  -93  -work eth ../../grlib-W2000A/lib/eth/core/greth_tx.vhd
	vcom -quiet  -93  -work eth ../../grlib-W2000A/lib/eth/core/greth_rx.vhd
	vcom -quiet  -93  -work eth ../../grlib-W2000A/lib/eth/core/grethc.vhd
	vcom -quiet  -93  -work eth ../../grlib-W2000A/lib/eth/wrapper/greth_gen.vhd
	vcom -quiet  -93  -work eth ../../grlib-W2000A/lib/eth/wrapper/greth_gbit_gen.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/occomp/occomp.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/can/cancomp.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/can/can_top.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/can/can_top_core_sync.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/i2c/i2c_master_bit_ctrl.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/i2c/i2c_master_byte_ctrl.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/i2c/i2coc.vhd
	vlog -quiet  -work opencores +incdir+../../grlib-W2000A/lib/opencores/spi ../../grlib-W2000A/lib/opencores/spi/simple_spi_top.v
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/ata/ud_cnt.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/ata/ro_cnt.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/ata/atahost_dma_fifo.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/ata/atahost_dma_actrl.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/ata/atahost_dma_tctrl.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/ata/atahost_pio_tctrl.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/ata/atahost_pio_actrl.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/ata/atahost_controller.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/ata/atahost_pio_controller.vhd
	vcom -quiet  -93  -work opencores ../../grlib-W2000A/lib/opencores/ata/ocidec2_controller.vhd
	vlog -quiet  -work opencores ../../grlib-W2000A/lib/opencores/ata/ata_device_oc.v
	vlog -quiet  -work opencores +incdir+../../grlib-W2000A/lib/opencores/ac97 ../../grlib-W2000A/lib/opencores/ac97/ac97_top.v
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/arith/arith.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/arith/mul32.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/arith/div32.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/memctrl/memctrl.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/memctrl/sdctrl.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/memctrl/sdmctrl.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/memctrl/srctrl.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/memctrl/spimctrl.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/leon3.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/mmuconfig.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/mmuiface.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/libmmu.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/libiu.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/libcache.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/libproc3.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/cachemem.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/mmu_icache.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/mmu_dcache.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/mmu_acache.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/mmutlbcam.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/mmulrue.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/mmulru.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/mmutlb.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/mmutw.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/mmu.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/mmu_cache.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/acache.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/dcache.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/icache.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/cache.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/cpu_disasx.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/iu3.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/grfpwx.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/mfpwx.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/grlfpwx.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/tbufmem.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/dsu3x.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/dsu3.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/proc3.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/leon3s.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/leon3cg.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/irqmp.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/grfpwxsh.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/grfpushwx.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/leon3/leon3sh.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/can/can.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/can/can_mod.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/can/can_oc.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/can/can_mc.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/can/canmux.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/can/can_rd.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/misc.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/rstgen.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/gptimer.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/ahbram.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/ahbdpram.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/ahbtrace.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/ahbmst.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/grgpio.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/ahbstat.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/logan.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/apbps2.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/charrom_package.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/charrom.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/apbvga.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/ahbdma.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/svgactrl.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/i2cmst.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/i2cmst_gen.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/spictrl.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/i2cslv.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/wild.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/wild2ahb.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/grsysmon.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/gracectrl.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/misc/grgpreg.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/net/net.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/uart/uart.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/uart/libdcom.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/uart/apbuart.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/uart/dcom.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/uart/dcom_uart.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/uart/ahbuart.vhd
	vlog -quiet  -work gaisler ../../grlib-W2000A/lib/gaisler/sim/i2c_slave_model.v
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/sim/sim.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/sim/sram.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/sim/ata_device.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/sim/sram16.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/sim/phy.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/sim/ahbrep.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/sim/delay_wire.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/sim/spi_flash.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/sim/pwm_check.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/sim/grusbdcsim.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/jtag/jtag.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/jtag/libjtagcom.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/jtag/jtagcom.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/jtag/ahbjtag.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/jtag/ahbjtag_bsd.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/jtag/jtagtst.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/greth/ethernet_mac.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/greth/greth.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/greth/greth_gbit.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/greth/grethm.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/usb/grusb.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/ata/ata.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/ata/ata_inf.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/ata/atahost_amba_slave.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/ata/atahost_ahbmst.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/ata/ocidec2_amba_slave.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/ata/atactrl_nodma.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/ata/atactrl_dma.vhd
	vcom -quiet  -93  -work gaisler ../../grlib-W2000A/lib/gaisler/ata/atactrl.vhd
	vcom -quiet  -93  -work esa ../../grlib-W2000A/lib/esa/memoryctrl/memoryctrl.vhd
	vcom -quiet  -93  -work esa ../../grlib-W2000A/lib/esa/memoryctrl/mctrl.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/clockgen/ge_clkgen_p.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/clockgen/clockgenerator_ea.vhd
	vlog -quiet  -work gleichmann +incdir+../../grlib-W2000A/lib/gleichmann/miscellaneous ../../grlib-W2000A/lib/gleichmann/miscellaneous/postponer.v
	vlog -quiet  -work gleichmann +incdir+../../grlib-W2000A/lib/gleichmann/miscellaneous ../../grlib-W2000A/lib/gleichmann/miscellaneous/ahb2wb.v
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/miscellaneous/miscellaneous_p.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/ahb2hpi/hpi_p.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/ahb2hpi/ahb2hpi2_ea.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/ahb2hpi/hpi_ram_ea.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/i2c/i2c.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/i2c/partoi2s.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/dac/dac_p.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/dac/dac_sigdelt_ea.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/dac/adc_sigdelt_ea.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/dac/adcdac_ea.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/dac/dac_ahb_ea.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/spi/sspi_p.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/spi/spi_oc_ea.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/spi/spi_p.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/spi/spi_xmit_ea.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/multiio/multiio_p.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/multiio/multiio_ea.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/ac97/ac97.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/ac97/ac97_oc.vhd
	vlog -quiet  -work gleichmann ../../grlib-W2000A/lib/gleichmann/sim/spi_slave_model.v
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/sim/txt_util.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/sim/phy_ext.vhd
	vcom -quiet  -93  -work gleichmann ../../grlib-W2000A/lib/gleichmann/sim/uart_ext.vhd
	vcom -quiet  -93  -work fmf ../../grlib-W2000A/lib/fmf/utilities/conversions.vhd
	vcom -quiet  -93  -work fmf ../../grlib-W2000A/lib/fmf/utilities/gen_utils.vhd
	vcom -quiet  -93  -work fmf ../../grlib-W2000A/lib/fmf/flash/flash.vhd
	vcom -quiet  -93  -work fmf ../../grlib-W2000A/lib/fmf/flash/s25fl064a.vhd
	vcom -quiet  -93  -work fmf ../../grlib-W2000A/lib/fmf/flash/m25p80.vhd
	vcom -quiet  -93  -work fmf ../../grlib-W2000A/lib/fmf/fifo/idt7202.vhd
	vcom -quiet  -93  -work gsi ../../grlib-W2000A/lib/gsi/ssram/functions.vhd
	vcom -quiet  -93  -work gsi ../../grlib-W2000A/lib/gsi/ssram/core_burst.vhd
	vcom -quiet  -93  -work gsi ../../grlib-W2000A/lib/gsi/ssram/g880e18bt.vhd
	vlog -quiet  -work micron ../../grlib-W2000A/lib/micron/sdram/mobile_sdr.v
	vcom -quiet  -93  -work micron ../../grlib-W2000A/lib/micron/sdram/components.vhd
	vcom -quiet  -93  -work micron ../../grlib-W2000A/lib/micron/sdram/mt48lc16m16a2.vhd
	vcom -quiet  -93  -work work ../../grlib-W2000A/lib/work/debug/debug.vhd
	vcom -quiet  -93  -work work ../../grlib-W2000A/lib/work/debug/grtestmod.vhd
	vcom -quiet  -93  -work work ../../grlib-W2000A/lib/work/debug/cpu_disas.vhd
#	vcom -quiet  -93  -work work config.vhd
#	vcom -quiet  -93  -work work ahbrom.vhd
#	vcom -quiet  -93  -work work W2000ROM.vhd
#	vcom -quiet  -93  -work work leon3mini.vhd
#	vcom -quiet  -93  -work work testbench.vhd
