vlib modelsim
vlib modelsim/grlib 
vlib modelsim/altera 
vlib modelsim/altera_mf 
vlib modelsim/dw02 
vlib modelsim/synplify 
vlib modelsim/techmap 
vlib modelsim/eth 
vlib modelsim/opencores 
vlib modelsim/gaisler 
vlib modelsim/esa 
vlib modelsim/gleichmann 
vlib modelsim/fmf 
vlib modelsim/spansion 
vlib modelsim/gsi 
vlib modelsim/DSO 
vlib modelsim/micron 
vlib modelsim/work 
